[build-system]
requires = ["setuptools",
            "setuptools_scm",
            "wheel"]
build-backend = 'setuptools.build_meta'

[project]
name = "exovetter"
version = "0.0.2"
authors = [{ names = "Susan Mullally"}]
readme = "README.rst"
license = {file="LICENSE"}
requires-python = ">=3.7"
